### ISSUE TITLE
Demo is outdated

### ISSUE THREAD

**Issue by ElMassimo** [Rich-Harris/svelte-knobby#19]
### Description 📖 

The [demo linked in the docs](https://svelte.dev/repl/85c0f69007524dd9a45a8bf72d2401ba?version=3.38.3) is no longer working with the latest version of the library, as it relies on a `knobby` export which is not available.

[This forked REPL](https://svelte.dev/repl/96d45da3ed3c4725af0751750f196bd3?version=3.38.3) replaces the `knobby` import with `panel`, and the demo works as expected.

Didn't submit a PR updating the README—I think you'll want to update your REPL instead to keep ownership 😄

**Comment by braebo** [comment]
Thanks @ElMassimo.  It seems changing the de-structured import to a wildcard like in the README also works in the svelte REPL.

Though neither worked on my REPL nor the MDSvex Playground until I pointed the import path to `utils.js`:
`import * as knobby from 'svelte-knobby@latest/utils.js'`

**Comment by Rich-Harris** [comment]
thanks — the README has since been updated
