### ISSUE TITLE
How to cross-reference control values?

### ISSUE THREAD

**Issue by braebo** [Rich-Harris/svelte-knobby#20]
I'm not sure the best way to do this.  I tried a few things like using `this` or anon functions and spreads to no avail.
Right now I get:
```js
const controls = knobby.panel({
    a: 20,
    b: a * 2    // a is not defined
})
```
And I'm not sure what the best way to consume them elsewhere is.  Perhaps:
```js
const stuff = (c) => constrols.a * c + controls.b   // or $controls.a/b?
// or
const { a, b } = $controls
const stuff = (c) => a * c + b
```
Any clarification would be much appreciated!  Sorry if I'm overlooking the obvious 😅

**Comment by Rich-Harris** [comment]
It sounds like you want `derived`: https://svelte.dev/tutorial/derived-stores

In some cases, like the `min` and `max` of a range value, you can also pass a function that takes the current store value as its input. Demo here: https://svelte.dev/repl/ecb3b08487b54182b58d19c465be6564?version=3.40.3

**Comment by braebo** [comment]
Ah yes- good idea!  This should cover my use case, I'll try it next time I've got the project open.  Thanks!
